package me.login.ordersystem.data;

import org.bukkit.inventory.ItemStack;
import java.util.UUID;
import java.util.concurrent.TimeUnit;

/**
 * Data class representing a single order.
 * (Moved to data sub-package for Point 13)
 */
public class Order {

    private long orderId;
    private final UUID placerUUID;
    private final String placerName;
    private final ItemStack item;
    private final int totalAmount;
    private final double pricePerItem;
    private int amountDelivered;
    private final long creationTimestamp;
    private final long expiryTimestamp;
    private OrderStatus status;

    public enum OrderStatus { ACTIVE, FILLED, EXPIRED, CANCELLED }

    // Constructor for NEW orders (ID generated by DB)
    public Order(UUID placerUUID, String placerName, ItemStack item, int totalAmount, double pricePerItem, long durationMillis) {
        this.orderId = -1; // Indicate ID not set yet
        this.placerUUID = placerUUID;
        this.placerName = placerName;
        this.item = item.clone();
        this.totalAmount = Math.max(1, totalAmount);
        this.pricePerItem = Math.max(0.0, pricePerItem);
        this.amountDelivered = 0;
        this.creationTimestamp = System.currentTimeMillis();
        this.expiryTimestamp = this.creationTimestamp + durationMillis;
        this.status = OrderStatus.ACTIVE;
    }

    // Constructor for LOADING orders from DB
    public Order(long orderId, UUID placerUUID, String placerName, ItemStack item, int totalAmount, double pricePerItem, int amountDelivered, long creationTimestamp, long expiryTimestamp, OrderStatus status) {
        this.orderId = orderId;
        this.placerUUID = placerUUID;
        this.placerName = placerName;
        this.item = item; // Assume item from DB is safe
        this.totalAmount = totalAmount;
        this.pricePerItem = pricePerItem;
        this.amountDelivered = amountDelivered;
        this.creationTimestamp = creationTimestamp;
        this.expiryTimestamp = expiryTimestamp;
        this.status = status;
    }


    // --- Getters ---
    public long getOrderId() { return orderId; }
    public UUID getPlacerUUID() { return placerUUID; }
    public String getPlacerName() { return placerName; }
    public ItemStack getItem() { return item.clone(); }
    public int getTotalAmount() { return totalAmount; }
    public double getPricePerItem() { return pricePerItem; }
    public int getAmountDelivered() { return amountDelivered; }
    public long getCreationTimestamp() { return creationTimestamp; }
    public long getExpiryTimestamp() { return expiryTimestamp; }
    public OrderStatus getStatus() { return status; }
    public double getTotalPrice() { return totalAmount * pricePerItem; }
    public double getAmountPaidByFillers() { return amountDelivered * pricePerItem; } // What fillers have earned

    public boolean isExpired() {
        if (status == OrderStatus.EXPIRED) return true;
        if (status != OrderStatus.ACTIVE) return false;
        return System.currentTimeMillis() > expiryTimestamp;
    }
    public boolean isFilled() { return amountDelivered >= totalAmount; }

    // --- Setters ---
    public void setOrderId(long orderId) { if (this.orderId == -1) this.orderId = orderId; }
    public void setAmountDelivered(int amountDelivered) {
        this.amountDelivered = Math.max(0, Math.min(totalAmount, amountDelivered));
        if (isFilled() && status == OrderStatus.ACTIVE) {
            this.status = OrderStatus.FILLED;
        }
    }
    public void setStatus(OrderStatus status) { this.status = status; }

    // --- Convenience Methods ---

    /**
     * Returns a string like "3d 12h 5m".
     * This is used for display in GUIs.
     */
    public String getFormattedExpiryTimeLeft() {
        long timeLeft = expiryTimestamp - System.currentTimeMillis();
        if (timeLeft <= 0 || status != OrderStatus.ACTIVE) {
            return switch (status) {
                case EXPIRED -> "Expired";
                case FILLED -> "Filled";
                case CANCELLED -> "Cancelled";
                default -> "N/A";
            };
        }
        long days = TimeUnit.MILLISECONDS.toDays(timeLeft); timeLeft -= TimeUnit.DAYS.toMillis(days);
        long hours = TimeUnit.MILLISECONDS.toHours(timeLeft); timeLeft -= TimeUnit.HOURS.toMillis(hours);
        long minutes = TimeUnit.MILLISECONDS.toMinutes(timeLeft);
        return String.format("%dd %dh %dm", days, hours, minutes);
    }

    /**
     * Gets the item's display name or a formatted material name.
     */
    public String getFormattedItemName() {
        if (item.hasItemMeta() && item.getItemMeta().hasDisplayName()) {
            // Note: This might return a legacy string. For 100% Kyori, this would need more work.
            // But for item names, this is generally safe.
            return item.getItemMeta().getDisplayName();
        }
        String name = item.getType().name().toLowerCase().replace("_", " ");
        return name.substring(0, 1).toUpperCase() + name.substring(1);
    }
}