name: Login
version: '1.0.0'
main: me.login.Login
api-version: '1.21'
depend: [Vault, Citizens, Skript, LuckPerms] # Hard dependencies
softdepend: [Essentials, PlaceholderAPI, Citizens ] # PAPI is already here, perfect!

commands:
  firesale:
    description: Manages the firesale system.
    aliases: [ fs ]
    permission: login.firesale.admin

  order:
    description: Manage item orders
    usage: /order create | /order menu | /order manage
    aliases: [orders]

  discord:
    description: Link your Minecraft account with Discord
    usage: /discord link
  unlink:
    description: UnLink your Minecraft account with Discord
    usage: /unlink
  adminunlink:
    description: Admin Command to unlink a Minecraft account
    usage: /adminunlink <player>

  commandhologram:
    description: Creates a command-based hologram.
    permission: mineaurora.command.hologram
    permission-message: You do not have permission to use this command.

  schedule:
    description: Schedules a server maintenance or restart.
    permission: login.admin.schedule
    usage: /schedule <maintenance|restart> <time>
  maintenance:
    description: Turns off maintenance mode.
    permission: login.admin.maintenance
    usage: /maintenance off
  worldmanager:
    description: Locks or unlocks a world.
    permission: login.admin.worldmanager
    usage: /worldmanager <lock|unlock> <worldname>

  register:
    description: Register your account
    usage: /register <password> <confirmPassword>
  login:
    description: Login to your account
    usage: /login <password>
  changepassword:
    description: Change your account password
    usage: /changepassword <oldPassword> <newPassword>
  unregister:
    description: Unregister a player (Admin)
    usage: /unregister <player>
  loginhistory:
    description: Check a player's login history (Admin)
    usage: /loginhistory <player>
  checkalt:
    description: Check for alternative accounts by IP (Admin)
    usage: /checkalt <player>
  adminchangepass:
    description: Force change a player's password and DM them (Admin)
    usage: /adminchangepass <player>

  scoreboard:
    description: Reloads the scoreboard configuration.
    usage: /scoreboard reload
    aliases: [sb]

  coinflip:
    description: Manage coinflip games.
    usage: /<command> create <heads/tails> <amount> | /<command> manage | /<command> help
    aliases: [ cf ]

  leaderboard:
    description: Spawns or reloads leaderboards.
    usage: /leaderboard <type|reload>
    permission: leaderboards.admin
    aliases: [ lb ]
  killleaderboard:
    description: Removes leaderboard displays of a specific type.
    usage: /killleaderboard <type|all>
    permission: leaderboards.admin
    aliases: [ klb, removeleaderboard ]

  lagclear:
    description: Manages the lag clearing utility.
    usage: /lagclear <clean>
    permission: lagclear.admin

  mute:
    description: Mutes a player for a specified duration.
    usage: /mute <player> <duration> <reason>
    permission: staff.mute
  muteinfo:
    description: Checks a player's active mute status.
    usage: /muteinfo <player>
    permission: staff.muteinfo
  unmute:
    description: Unmutes a player.
    usage: /unmute <player>
    permission: staff.unmute
  ban:
    description: Bans a player for a specified duration.
    usage: /ban <player> <duration> <reason>
    permission: staff.ban
  ipban:
    description: IP-Bans an online player for a specified duration.
    usage: /ipban <player> <duration> <reason>
    permission: staff.ipban
  baninfo:
    description: Checks a player's active ban status.
    usage: /baninfo <player>
    permission: staff.baninfo
  unban:
    description: Unbans a player (by name/UUID).
    usage: /unban <player>
    permission: staff.unban
  unbanip:
    description: Unbans an IP address.
    usage: /unbanip <ip_address>
    permission: staff.unbanip
  checkinv:
    description: Opens a read-only view of a player's inventory.
    usage: /checkinv <player>
    permission: staff.checkinv
  admincheckinv:
    description: Opens a view of a player's inventory, allowing item removal.
    usage: /admincheckinv <player>
    permission: staff.admincheckinv

  withdrawhearts:
    description: Withdraws hearts as items.
    usage: /withdrawhearts <amount>
    permission: lifesteal.withdraw

  lifesteal:
    description: Lifesteal main command.
    usage: /lifesteal <give|sethearts|checkhearts|revive>
    aliases: [ls]

  dailyreward:
    description: Claim your daily reward.
    usage: /dailyreward
    aliases: [dr]

  playtimerewards:
    description: Claim your playtime rewards.
    usage: /playtimerewards
    aliases: [ptrewards]

  tokenshop:
    description: Opens the token shop.
    usage: /tokenshop
  token:
    description: Manage your tokens or admin tokens.
    usage: /token <balance|add|remove|set>

  creditcode:
    description: Apply a creator code.
    usage: /creditcode
    aliases: [applycreatorcode]
  creatorcode:
    description: Admin command to manage creator codes.
    usage: /creatorcode <add|remove|list>
    permission: login.creatorcode.admin
  removecreditcode:
    description: Admin command to remove a creator code.
    usage: /removecreditcode <name>
    permission: login.creatorcode.admin

  rank:
    description: Manages player ranks.
    usage: /rank <set|remove|info>
    permission: login.rank.admin

permissions:
  logincore.admin:
    description: Allows use of /unregister
    default: op
  logincore.loginhistory:
    description: Allows use of /loginhistory
    default: op
  logincore.checkalt:
    description: Allows use of /checkalt
    default: op
  logincore.adminchangepass:
    description: Allows use of /adminchangepass
    default: op

  discord.unlink.admin:
    description: Allows use of /adminunlink
    default: op

  login.scoreboard.reload:
    description: Allows use of /scoreboard reload command.
    default: op

  leaderboards.admin:
    description: Allows users to create and manage leaderboards.
    default: op

  lagclear.admin:
    description: Allows use of the /lagclear command.
    default: op

  staff.staff:
    description: Receives staff-wide broadcast messages.
    default: op
  staff.mute:
    description: Allows muting players.
    default: op
  staff.muteinfo:
    description: Allows checking mute status.
    default: op
  staff.unmute:
    description: Allows unmuting players.
    default: op
  staff.ban:
    description: Allows banning players.
    default: op
  staff.ipban:
    description: Allows IP banning players.
    default: op
  staff.baninfo:
    description: Allows checking ban status.
    default: op
  staff.unban:
    description: Allows unbanning players.
    default: op
  staff.unbanip:
    description: Allows unbanning IPs.
    default: op
  staff.checkinv:
    description: Allows read-only inventory checks.
    default: op
  staff.admincheckinv:
    description: Allows admin inventory checks (item removal).
    default: op

  lifesteal.withdraw:
    description: Allows player to withdraw hearts.
    default: op
  lifesteal.check:
    description: Allows player to use /ls checkhearts.
    default: op
  lifesteal.revive:
    description: Allows player to use the revive beacon.
    default: op
  lifesteal.admin.give:
    description: Allows admin to use /ls give.
    default: op
  lifesteal.admin.set:
    description: Allows admin to use /ls sethearts.
    default: op
  lifesteal.admin.revive:
    description: Allows admin to use /ls revive.
    default: op

  mineaurora.dailyreward.rank:
    description: Allows player to open the ranked daily reward GUI.
    default: op
  mineaurora.dailyreward.elite:
    description: Permission for the Elite daily reward.
    default: op
  mineaurora.dailyreward.ace:
    description: Permission for the Ace daily reward.
    default: op
  mineaurora.dailyreward.overlord:
    description: Permission for the Overlord daily reward.
    default: op
  mineaurora.dailyreward.immortal:
    description: Permission for the Immortal daily reward.
    default: op
  mineaurora.dailyreward.supreme:
    description: Permission for the Supreme daily reward.
    default: op
  mineaurora.dailyreward.phantom:
    description: Permission for the Phantom daily reward.
    default: op

  token.admin:
    description: Allows use of /token <add|remove|set>
    default: op

  login.creatorcode.use:
    description: Allows players to use /creditcode.
    default: true
  login.creatorcode.admin:
    description: Allows admins to manage creator codes.
    default: op

  login.rank.admin:
    description: Allows admins to manage player ranks with /rank.
    default: op
