package me.login.ordersystem;

import org.bukkit.inventory.ItemStack;
import java.util.UUID;
import java.util.concurrent.TimeUnit;

public class Order {

    private long orderId; // Changed to long
    private final UUID placerUUID;
    private final String placerName;
    private final ItemStack item;
    private final int totalAmount;
    private final double pricePerItem;
    private int amountDelivered;
    // REMOVED: claimedAmount
    private final long creationTimestamp;
    private final long expiryTimestamp;
    private OrderStatus status;

    public enum OrderStatus { ACTIVE, FILLED, EXPIRED, CANCELLED }

    // Constructor for NEW orders (ID generated by DB)
    public Order(UUID placerUUID, String placerName, ItemStack item, int totalAmount, double pricePerItem, long durationMillis) {
        this.orderId = -1; // Indicate ID not set yet
        this.placerUUID = placerUUID;
        this.placerName = placerName;
        this.item = item.clone();
        this.totalAmount = Math.max(1, totalAmount);
        this.pricePerItem = Math.max(0.0, pricePerItem);
        this.amountDelivered = 0;
        // REMOVED: claimedAmount
        this.creationTimestamp = System.currentTimeMillis();
        this.expiryTimestamp = this.creationTimestamp + durationMillis;
        this.status = OrderStatus.ACTIVE;
    }

    // Constructor for LOADING orders from DB (REMOVED claimedAmount)
    public Order(long orderId, UUID placerUUID, String placerName, ItemStack item, int totalAmount, double pricePerItem, int amountDelivered, long creationTimestamp, long expiryTimestamp, OrderStatus status) {
        this.orderId = orderId;
        this.placerUUID = placerUUID;
        this.placerName = placerName;
        this.item = item; // Assume item from DB is safe
        this.totalAmount = totalAmount;
        this.pricePerItem = pricePerItem;
        this.amountDelivered = amountDelivered;
        // REMOVED: claimedAmount
        this.creationTimestamp = creationTimestamp;
        this.expiryTimestamp = expiryTimestamp;
        this.status = status;
    }


    // --- Getters ---
    public long getOrderId() { return orderId; }
    public UUID getPlacerUUID() { return placerUUID; }
    public String getPlacerName() { return placerName; }
    public ItemStack getItem() { return item.clone(); }
    public int getTotalAmount() { return totalAmount; }
    public double getPricePerItem() { return pricePerItem; }
    public int getAmountDelivered() { return amountDelivered; }
    // REMOVED: getClaimedAmount()
    public long getCreationTimestamp() { return creationTimestamp; }
    public long getExpiryTimestamp() { return expiryTimestamp; }
    public OrderStatus getStatus() { return status; }
    public double getTotalPrice() { return totalAmount * pricePerItem; }
    public double getAmountPaidByFillers() { return amountDelivered * pricePerItem; } // What fillers have earned
    // REMOVED: getPaymentDueToPlacer()
    public boolean isExpired() {
        if (status == OrderStatus.EXPIRED) return true;
        if (status != OrderStatus.ACTIVE) return false;
        boolean expired = System.currentTimeMillis() > expiryTimestamp;
        // Auto-update status if expired (will be saved on next interaction or cleanup task)
        // if (expired) status = OrderStatus.EXPIRED; // Let DB handle this
        return expired;
    }
    public boolean isFilled() { return amountDelivered >= totalAmount; }

    // --- Setters ---
    public void setOrderId(long orderId) { if (this.orderId == -1) this.orderId = orderId; }
    public void setAmountDelivered(int amountDelivered) {
        this.amountDelivered = Math.max(0, Math.min(totalAmount, amountDelivered));
        if (isFilled() && status == OrderStatus.ACTIVE) {
            this.status = OrderStatus.FILLED;
        }
    }
    // REMOVED: setClaimedAmount()
    public void setStatus(OrderStatus status) { this.status = status; }

    // --- Convenience Methods ---
    public String getFormattedExpiryTimeLeft() {
        long timeLeft = expiryTimestamp - System.currentTimeMillis();
        if (timeLeft <= 0 || status != OrderStatus.ACTIVE) {
            // Show status instead of time if not active/expired
            return switch (status) {
                case EXPIRED -> "Expired";
                case FILLED -> "Filled";
                case CANCELLED -> "Cancelled";
                default -> "N/A";
            };
        }
        long days = TimeUnit.MILLISECONDS.toDays(timeLeft); timeLeft -= TimeUnit.DAYS.toMillis(days);
        long hours = TimeUnit.MILLISECONDS.toHours(timeLeft); timeLeft -= TimeUnit.HOURS.toMillis(hours);
        long minutes = TimeUnit.MILLISECONDS.toMinutes(timeLeft);
        return String.format("%dd %dh %dm", days, hours, minutes);
    }
    public String getFormattedItemName() {
        if (item.hasItemMeta() && item.getItemMeta().hasDisplayName()) return item.getItemMeta().getDisplayName();
        String name = item.getType().name().toLowerCase().replace("_", " "); return name.substring(0, 1).toUpperCase() + name.substring(1);
    }
}